title: "Header"
description: |
  The main navigation for the website.
patterns:
  navbar:
    height: 400
    fields:
      - name: profileImg
        type: string
        example: profile-owner.jpg
      - name: pageBanner
        type: boolean
        example: false
