title: "Cards"
description: |
  A collection of card options.
patterns:
  profile-card:
    title: "Profile Card"
    width: 400
    padding: 20px
    fields:
      - name: profileImg
        type: string
        example: "profile-hugh.jpg"
      - name: topSitter
        type: boolean
        example: true
      - name: name
        type: string
        example: "Hugh Andrews"
      - name: location
        type: string
        example: "Ottawa, ON"
      - name: link
        type: string
        example: "#"
      - name: rating
        type: number
        example: 4
      - name: bio
        type: string
        example: "Hi! I have been dog sitting for over 5 years and would love to meet your dog!"
  review:
    title: "Review Card"
    width: 600
    padding: 20px
    fields:
      - name: profileImg
        type: string
        example: "profile-hugh.jpg"
      - name: rating
        type: number
        example: 4
      - name: reviewTitle
        type: string
        example: Best sitter ever!
      - name: reviewText
        type: string
        example: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  signin:
    title: "Sign In"
    width: 450
    padding: 20px
  my-bookings:
    width: 500
    fields:
      - name: booking-title
        type: string
        example: Booking Requested
      - name: profileImg
        type: string
        example: profile-helen.jpg
      - name: sitter-name
        type: string
        example: Helen Jones
      - name: booking-dates
        type: string
        example: April 20 - April 22
      - name: location
        type: string
        example: Ottawa, ON
      - name: status
        type: string
        example: Booking confirmed
  booking-requested:
    width: 600
    fields:
      - name: profileImg
        type: string
        example: profile-helen.jpg
      - name: sitter-name
        type: string
        example: Helen Jones
      - name: booking-dates
        type: string
        example: April 4 — April 6, 2019
