title: "Accordion"
description: |
  A basic expanding according for FAQs and other content.
patterns:
  accordion:
    title: "Accordion"
    fields:
      - name: title
        type: string
        example: "Accordion Title"
      - name: text
        type: markdown
        example: |
          ### Accordion text

          Hello there friends!
