title: "Photo Array"
description: |
  Responsive photo grid for users to share pet-related photos on their profiles.
patterns:
  photo-array:
    fields:
      - name: photo1
        type: string
        example: /images/house01.jpg
      - name: photo2
        type: string
        example: /images/house02.jpg
      - name: photo3
        type: string
        example: /images/house03.jpg
      - name: photo4
        type: string
        example: /images/house04.jpg
      - name: photo5
        type: string
        example: /images/house05.jpg
      - name: photo6
        type: string
        example: /images/house06.jpg
