title: "Rating Scale"
description: |
  A basic rating scale that can be adjusted in each use.
patterns:
  rating:
    title: "Rating Scale"
    fields:
      - name: rating
        type: number
        example: 4
      - name: color
        type: string
        example: "primary"
      - name: divClass
        type: string
        example: "pad-b"
      - name: iconSize
        type: string
        example: "i-1"
