title: "Profile Photo"
description: |
  A profile photo used for accounts.
patterns:
  profile-photo:
    width:
    fields:
      - name: profileImg
        type: string
        example: "profile-helen.jpg"
      - name: size
        type: string
        example: "5rem"
      - name: borderColor
        type: string
        example: "var(--color-grey-dark)"
        required: false
      - name: wrapClass
        type: string
        example: ""
        required: false
